# Generated by Django 5.2.3 on 2025-07-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='epic_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
