# Generated by Django 5.2.3 on 2025-07-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='household_head',
        ),
        migrations.AddField(
            model_name='person',
            name='is_househead',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
