# Generated by Django 5.2.3 on 2025-07-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_remove_house_household_head_person_is_househead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='rent_end_date',
        ),
        migrations.RemoveField(
            model_name='house',
            name='rent_start_date',
        ),
        migrations.AddField(
            model_name='person',
            name='rent_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='rent_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
