# Generated by Django 5.2.3 on 2025-07-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_remove_house_rent_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
    ]
