# Generated by Django 5.2.3 on 2025-06-29 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=20, unique=True)),
                ('veng', models.CharField(max_length=100)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('landmarks', models.CharField(blank=True, max_length=100, null=True)),
                ('is_owner', models.BooleanField(default=True)),
                ('lsc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('awmtan_kum', models.PositiveBigIntegerField(blank=True, null=True)),
                ('pem_luh_chhan', models.CharField(blank=True, max_length=255, null=True)),
                ('have_tenant', models.BooleanField(default=False)),
                ('household_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_tenant', models.BooleanField(default=False)),
                ('landlord_name', models.CharField(blank=True, max_length=100, null=True)),
                ('landlord_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('landlord_veng', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_units', to='kyc.house')),
            ],
        ),
        migrations.CreateModel(
            name='HouseMaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('veng', models.CharField(max_length=100)),
                ('epic_number', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maids', to='kyc.house')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('hnam_hming', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Other', 'Other')], max_length=15)),
                ('dob', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('epic_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=50)),
                ('denomination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyc.denomination')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyc.education')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_by_father', to='kyc.person')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyc.house')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_by_mother', to='kyc.person')),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_of', to='kyc.person')),
                ('religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyc.religion')),
            ],
        ),
        migrations.AddField(
            model_name='denomination',
            name='religion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='kyc.religion'),
        ),
    ]
