# Generated by Django 5.2.3 on 2025-07-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denomination',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
