# Generated by Django 5.2.3 on 2025-07-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_denomination_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denomination',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
