# Generated by Django 5.2.3 on 2025-07-14 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("certificates", "0001_initial"),
        ("core", "0001_initial"),
        ("kyc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="citizen_locality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.veng",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="kyc.person",
            ),
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="certificate_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="certificates.certificatetype",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="certificate_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="certificates.certificatetype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="certificatetemplate",
            unique_together={("certificate_type", "name")},
        ),
    ]
