# Generated by Django 5.2.3 on 2025-07-15 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_initial"),
        ("kyc", "0002_remove_house_household_head_person_is_househead"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="certificatetemplate",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="certificatetemplate",
            name="certificate_type",
        ),
        migrations.AddField(
            model_name="certificatetype",
            name="template",
            field=models.TextField(
                default="",
                help_text="Use placeholders like {{ person.name }}, {{ person.permanent_address }}",
            ),
        ),
        migrations.CreateModel(
            name="IssuedCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("application_date", models.DateField(auto_now_add=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("issued_by", models.CharField(blank=True, max_length=100, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "certificate_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_certificates",
                        to="certificates.certificatetype",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_certificates",
                        to="kyc.person",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Certificate",
        ),
        migrations.DeleteModel(
            name="CertificateTemplate",
        ),
    ]
