# Generated by Django 5.2.3 on 2025-07-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0003_alter_certificatetemplate_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatetype",
            name="variables",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="List of variables used in the template",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issuedcertificate",
            name="variables",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Variables used in the certificate content",
                null=True,
            ),
        ),
    ]
