# Generated by Django 5.2.3 on 2025-07-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0004_certificatetype_variables_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificatetype",
            name="template",
            field=models.JSONField(
                default=dict, help_text="Quill Delta for the certificate template"
            ),
        ),
        migrations.AlterField(
            model_name="issuedcertificate",
            name="content",
            field=models.JSONField(),
        ),
    ]
