# Generated by Django 5.2.3 on 2025-07-16 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0005_alter_certificatetype_template_and_more"),
        ("kyc", "0002_remove_house_household_head_person_is_househead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuedcertificate",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issued_certificates",
                to="kyc.person",
            ),
        ),
    ]
